import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {

  function calculatePercentage() {
      const inputServico = document.getElementById("valorServico");

      const valorServico = inputServico.value;

      const InputoPorcentagemInicial = document.getElementById("porcentagem");

      const porcentagemInicial = InputoPorcentagemInicial.value;

      const porcentagemFinal = porcentagemInicial / 100 ;

      const calculo = parseFloat(valorServico) + parseFloat(valorServico * porcentagemFinal);

      document.getElementById("lblValorFinal").setAttribute("value", calculo);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Gerador de Orçamento</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{ marginTop: '180px' }}>
          Bem-vindo
          </h1>

        <p className={styles.description}>
          Prestador de serviço, esse é o seu gerador de orçamentos online
          </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Faça seu orçamento aqui!</h2>
            <div>
              <input type="text" placeholder="Digite seu nome" name="nome" id="nome" className="form-control mb-3" />
              <input type="text" placeholder="Digite seu cpf/cnpj" id="cpfcnpj" className="form-control mb-3" />
              <input type="text" placeholder="Digite o valor do serviço" id="valorServico" className="form-control mb-3" />
              <input type="text" placeholder="Digite a porcentagem da mão de obra" id="porcentagem" className="form-control mb-3" />
            </div>
            <div>
              <button type="button" className="btn btn-primary" id="btnCalcular" onClick={calculatePercentage}>Calcular</button>
            </div>
            <div  id="valorFinalOrcamento">
              <p>O valor final de seu orçamento é - R$ <span id="lblValorFinal"></span></p>
            </div>
          </div>
          <div className={styles.card}>
            <a href="https://github.com/joao03araujo">
              <h2>Visite meu GitHub &rarr;</h2>
              <p>Lá tem esse e outros projetos com Node.js e Next.js</p>
            </a>
          </div>
        </div>
      </main>
    </div>
  )
}
